[package]
name = "Chess_Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
eframe = "0.22.0"  # Includes egui
image = "0.24.7"
egui = "0.22.0"   # For piece images

[dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
]